futbol/urls.py
from django.urls import path
from futbol.views.pages.league_page import LeaguePageView
from futbol.views.pages.news_detail import NewsDetailView
from futbol.views.pages.regulation_page import RegulationPageView

from futbol.views.pages.schedule_menu_option_page import ScheduleMenuOptionPageView
from futbol.views.pages.standings_menu_option_page import  StandingsMenuOptionPageView
from futbol.views.pages.stats_menu_option_page import StatsMenuOptionPageView
from futbol.views.pages.team_details_page import TeamDetailsPageView
from futbol.views.pages.teams_page import TeamsPageView
from .views.pages.home_page import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="landing_page"),
    path("regulation/", RegulationPageView.as_view(), name="regulation_page"),

    path("league/<slug:league_slug>/", LeaguePageView.as_view(), name="league_page"),

    path("teams/<slug:league_slug>/", TeamsPageView.as_view(), name="teams_page"),

    path("schedule/<str:league_slug>/", ScheduleMenuOptionPageView.as_view(), name="schedule_page"),
    path("standing/<slug:league_slug>", StandingsMenuOptionPageView.as_view(), name="standing_page"),
    path("stats/<slug:league_slug>", StatsMenuOptionPageView.as_view(), name="stats_page"),
    path("team-details/<slug:league_slug>/<slug:team_slug>", TeamDetailsPageView.as_view(), name="team_details_page"),
   
    path('news/<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
 ]

marxleague/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("", include("futbol.urls")),  # Home entre otros....
    path("admin/", admin.site.urls),
   
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

futbol/models.py
# Create your models here.

futbol/models/goal.py
from pyexpat import model
from django.db import models

from futbol.models.player import Player
from futbol.models.schedule import Schedule


# Goal
class Goal(models.Model):
    min = models.CharField(max_length=2, null=True, blank=True)
    player = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True)
    schedule = models.ForeignKey(Schedule, on_delete=models.SET_NULL, null=True)
    penalty = models.BooleanField()
    definition_of_penalties = (
        models.BooleanField()
    )  # Se utiliza si los peniltis son marcados para la definicion del partido

    def __str__(self):
        penalty_type = "Penalty" if self.penalty else "Goal"
        schedule_info = f"{self.schedule.date} - {self.schedule.hc.name} vs {self.schedule.vs.name}"
        return f"{self.player.name} - {penalty_type} at {self.min} minutes "

futbol/models/league.py
from django.db import models



# Teams
class League(models.Model):
    name = models.CharField(max_length=100, unique=True, default="Nombre")
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)
    
    teams = models.ManyToManyField('Team', related_name='leagues')

    def __str__(self):
        return self.name

futbol/models/news.py
from django.db import models
import os


def image_upload_path(instance, filename):
    ext = filename.split('.')[-1]
    new_filename = 'uno.{}'.format(ext)
    return os.path.join('news/', new_filename)

class News(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    author = models.CharField(max_length=100, null=True, blank=True)
    image = models.ImageField(upload_to=image_upload_path, null=True, blank=True)
    caption = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.title
    
    

futbol/models/player.py
from django.db import models


from .team import Team
from .league import League


# PLayers
class Player(models.Model):
    name = models.CharField(max_length=100, unique=True, default="Nombre")
    grade = models.CharField(max_length=50, null=True, blank=True)

    imagen = models.CharField(max_length=100, null=True, blank=True)
    alias = models.CharField(max_length=50, null=True, blank=True)
    
    def __str__(self):
        return self.name

futbol/models/player_league_team.py
from django.db import models

from .player import Player
from .team import Team
from .league import League

class PlayerLeagueTeam(models.Model):

    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    league = models.ForeignKey(League, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.player.name} - {self.league.name} - {self.team.name}"

futbol/models/schedule.py
from django.db import models

from .player import Player
from .team import Team
from .league import League


class Schedule(models.Model):
    STATUS_CHOICES = [
        ("completed", "Completed"),
        ("scheduled", "Scheduled"),
        ("raining", "Raining"),
        ("playing", "Playing"),
        ("pending", "Pending"),
    ]
    STAGES_CHOICES = [
        ("regular", "Regular"),
        ("octavos", "Octavos"),
        ("cuartos", "Cuartos"),
        ("semifinal", "SemiFinal"),
        ("final", "Final"),
    ]

    league = models.ForeignKey(League, on_delete=models.SET_NULL, null=True)

    vs = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        related_name="vs_schedule",
        null=True,
        blank=True,
    )

    hc = models.ForeignKey(
        Team,
        on_delete=models.SET_NULL,
        related_name="hc_schedule",
        null=True,
        blank=True,
    )
    date = models.DateField(null=True, blank=True)

    vs_goals = models.IntegerField(null=True, blank=True, default=0)
    hc_goals = models.IntegerField(null=True, blank=True, default=0)

    vs_definition_penalties = models.IntegerField(null=True, blank=True, default=0)
    hc_definition_penalties = models.IntegerField(null=True, blank=True, default=0)

    # vs_points = models.IntegerField(null=True, blank=True, default=0)
    # hc_points = models.IntegerField(null=True, blank=True, default=0)

    mvp = models.ForeignKey(Player, on_delete=models.SET_NULL, null=True, blank=True)

    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default="scheduled"
    )

    stages = models.CharField(max_length=20, choices=STAGES_CHOICES, default="regular")


    def __str__(self):
        return str(self.league.name) + ': ' + self.hc.name + ' - ' + self.vs.name + ' - ' + self.date.strftime("%d %B")

futbol/models/team.py
from django.db import models

from futbol.models.league import League


# Teams
class Team(models.Model):
    name = models.CharField(max_length=100, unique=True, null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True, blank=True, null=True)
    # name1 = models.CharField(max_length=100, unique=False, null=True, blank=True)

    grade = models.CharField(max_length=50, null=True, blank=True)
    abbrev = models.CharField(max_length=3, null=True, blank=True)
    imagen = models.CharField(max_length=3, null=True, blank=True)

    def __str__(self):
        return self.name

futbol/views.py
from django.shortcuts import render

# Create your views here.

futbol/views/views/news_list_view.py
from django.views.generic import TemplateView
from futbol.models.news import News

class NewsListView(TemplateView):
    # model = News
    template_name = 'views/news_list_view.html'
    # context_object_name = 'news_list'
    # paginate_by = 10  # Si deseas paginar los resultados

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        news_list = News.objects.all()

        context['news_list'] = news_list
        return context

futbol/views/views/schedule_view.py
from datetime import date
from django.views.generic import TemplateView
from django.db.models import Q
from futbol.models.league import League
from futbol.models.schedule import Schedule
from futbol.models.team import Team

class ScheduleView(TemplateView):
    template_name = "views/schedule_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        schedules = Schedule.objects.all()
        if '_from' in kwargs and '_to' in kwargs:
            _from = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_from']  
            _to = date.today().strftime("%Y-%m-%d") if kwargs['_to'] == 'today' else kwargs['_to']
            schedules = Schedule.objects.filter(date__range=[_from, _to])
        elif '_from' in kwargs: 
            _from = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_from']  
            schedules = Schedule.objects.filter(date__gte=_from)
        elif '_to' in kwargs: 
            _to = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_to']  
            schedules = Schedule.objects.filter( date__lte=_to)

            
        if 'team_slug' in kwargs:
            team = Team.objects.get(slug=kwargs['team_slug'])
            schedules = schedules.filter(Q(vs=team) | Q(hc=team))
            context['team'] = team

        if 'league_slug' in kwargs:
            league = League.objects.get(slug=kwargs.get('league_slug'))
            schedules = schedules.filter(league__slug=kwargs.get('league_slug'))
            context['league'] = league

        schedules = schedules.order_by('-date')

        if 'limit' in kwargs:  # limit
            schedules = schedules[:kwargs.get('limit')]


        if 'details' in kwargs:
            context['show_details'] = True

        context['schedules'] = schedules

        return context

futbol/views/views/standing_view.py
from datetime import date
from django.views.generic import TemplateView
from django.db.models import Q
from futbol.models.goal import Goal
from django.db.models import Sum, Case, When, IntegerField, Count
from futbol.models.league import League
from futbol.models.standing import Standing

from futbol.models.team import Team

class StandingView(TemplateView):
    template_name = "views/standing_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        league = League.objects.get(slug=kwargs.get('league_slug'))
        
        standings = standings = Standing.objects.filter(league=league)
      
        if 'league_slug' in kwargs:
            league = League.objects.get(slug=kwargs.get('league_slug'))
            # schedules = schedules.filter(league__slug=kwargs.get('league_slug'))
            context['league'] = league

        standings = standings.order_by('-pts', '-gdif')

        if 'limit' in kwargs:  # limit
            standings = standings[:kwargs.get('limit')]


        # if 'details' in kwargs:
        #     context['show_details'] = True

        context['standings'] = standings

        return context


  # if '_from' in kwargs and '_to' in kwargs:
        #     _from = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_from']  
        #     _to = date.today().strftime("%Y-%m-%d") if kwargs['_to'] == 'today' else kwargs['_to']
        #     schedules = Schedule.objects.filter(date__range=[_from, _to])
        # elif '_from' in kwargs: 
        #     _from = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_from']  
        #     schedules = Schedule.objects.filter(date__gte=_from)
        # elif '_to' in kwargs: 
        #     _to = date.today().strftime("%Y-%m-%d") if kwargs['_from'] == 'today' else kwargs['_to']  
        #     schedules = Schedule.objects.filter( date__lte=_to)

            
        # if 'team_slug' in kwargs:
        #     team = Team.objects.get(slug=kwargs['team_slug'])
        #     schedules = schedules.filter(Q(vs=team) | Q(hc=team))
        #     context['team'] = team

futbol/views/views/stats_goals_view.py
from datetime import date
from django.views.generic import TemplateView
from django.db.models import Q
from futbol.models.goal import Goal
from django.db.models import Sum, Case, When, IntegerField, Count
from futbol.models.league import League

from futbol.models.team import Team

class StatsGoalsView(TemplateView):
    template_name = "views/stats_goals_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        goals = Goal.objects

        if 'league_slug' in kwargs:
            league = League.objects.get(slug=kwargs.get('league_slug'))
            goals = goals.filter(schedule__league=league, player__playerleagueteam__league=league)
            context['league'] = league

        if 'team_slug' in kwargs:
            team = Team.objects.get(slug=kwargs['team_slug'])
            goals = goals.filter(Q(schedule__vs=team) | Q(schedule__hc=team))
            goals = goals.filter(Q(player__playerleagueteam__team=team) & Q(player__playerleagueteam__league=league))                       
            context['team'] = team

        goals = goals.select_related('player', 'player__playerleagueteam__team')

        goals = goals.values('player', 'player__name', 'player__playerleagueteam__team__imagen'
        ).annotate(
            goals=Count('player'),
            penalties=Sum(Case(When(penalty=True, then=1), default=0, output_field=IntegerField()))
        ).order_by('-goals')

        # str = goals.query
        # print(str)

        if 'limit' in kwargs:  # limit
            goals = goals[:kwargs.get('limit')]

        context['goals'] = goals
        
        return context

futbol/templates/views/news_list_view.html
{% for news in news_list %}
  <div class="card mb-3">
    <div class="row g-0">
      <div class="col-md-4">
        {% if news.image %}
          <img src="{{ news.image.url }}" class="card-img" alt="{{ news.title }}" />
        {% else %}
          <img src="/media/news/na.jpeg" class="card-img" alt="Default Image" />
        {% endif %}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h2 class="card-title">{{ news.title }}</h2>
          <p class="card-text">{{ news.body|truncatewords:20 }}</p>
          <a href="{% url 'news_detail' news.id %}" class="btn btn-outline-secondary">Leer más</a>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

futbol/templates/views/schedule_view.html
{% load static %}
<div class="card-deck">
  {% for schedule in schedules %}
    <div class="card mb-4">
      <div class="card-body shadow-sm">
        <div class="d-flex justify-content-between align-items-center">
          <div class="text-center flex-fill">
            <img style="height: 32px; width: 32px" src="{% static 'futbol/images/logos/' %}{{ schedule.hc.imagen|default:'na' }}.png" class="rounded" alt="Logo" />
            <br />
            <a href="{% url 'team_details_page' league.slug schedule.hc.slug %}">{{ schedule.hc }}</a>
          </div>
          <div class="text-center flex-fill">
            <div class="fw-bold fs-2 text-center">
              {% if schedule.hc_goals is not None %}
                {{ schedule.hc_goals }}
              {% endif %}
              {% if schedule.hc_definition_penalties > 0 %}
                <div class="fs-5 text-secondary text-center">
                  ({{ schedule.hc_definition_penalties }})
                </div>
              {% endif %}
            </div>
          </div>
          <div class="text-center flex-fill">
            <p class="card-text">{{ schedule.date|date:"d/m" }}</p>
            <p class="card-text">{{ schedule.status }}</p>
          </div>
          <div class="flex-fill">
            <div class="fw-bold fs-2 text-center">
              {% if schedule.vs_goals is not None %}
                {{ schedule.vs_goals }}
              {% endif %}
              {% if schedule.vs_definition_penalties > 0 %}
                <div class="fs-5 text-secondary text-center">
                  ({{ schedule.vs_definition_penalties }})
                </div>
              {% endif %}
            </div>
          </div>
         
          <div class="text-center flex-fill">
            <img style="height: 32px; width: 32px" src="{% static 'futbol/images/logos/' %}{{ schedule.vs.imagen|default:'na' }}.png" class="rounded" alt="Logo" />
            <br />
            <a href="{% url 'team_details_page' league.slug schedule.vs.slug %}">{{ schedule.vs }}</a>
          </div>
        </div>
        {% if show_details %}
          <hr />
          <div class="text-center">
            {% if schedule.mvp %}
              <b>MVP:</b> {{ schedule.mvp.name }} <br />
            {% endif %}
            {% if schedule.goal_set.all %}
              <b>Goles:</b>
              <p>
                {% for goal in schedule.goal_set.all %}
                  {{ goal.player.name }}
                  {% if not forloop.last %}, {% endif %}
                {% endfor %}
              </p>
            {% endif %}
          </div>
        {% endif %}
      </div>
    </div>
  {% endfor %}
</div>

futbol/templates/views/standing_view.html
{% load static %}

<table class="table table-bordered table-condensed shadow-sm">
  <thead>
    <tr>
      <th class="text-center">Orden</th>
      <th class="text-center"></th>
      <th class="text-center">Equipo</th>
      <th class="text-center">Ptos</th>
      <th class="text-center">PJ</th>
      <th class="text-center">PG</th>
      <th class="text-center">PE</th>
      <th class="text-center">PP</th>
      <th class="text-center">GF</th>
      <th class="text-center">GC</th>
      <th class="text-center">Dif</th>
    </tr>
  </thead>
  <tbody>
    {% for standing in standings %}
      <tr {% if forloop.counter <= 8 %}style="background-color: #ADD8E6;"{% endif %}>
        <td class="text-center align-middle" >{{ forloop.counter }}</td>
        <td class="text-center align-middle">
          <img style="height: 24; width: 24px" src="{% static 'futbol/images/logos/' %}{{ standing.team.imagen|default:'na' }}.png" class="rounded" alt="Logo" />
        </td>
        <td class="text-center align-middle">{{ standing.team }}</td>
        <td class="text-center align-middle">{{ standing.pts }}</td>
        <td class="text-center align-middle">{{ standing.pj }}</td>
        <td class="text-center align-middle">{{ standing.pg }}</td>
        <td class="text-center align-middle">{{ standing.pe }}</td>
        <td class="text-center align-middle">{{ standing.pp }}</td>
        <td class="text-center align-middle">{{ standing.gf }}</td>
        <td class="text-center align-middle">{{ standing.gc }}</td>
        <td class="text-center align-middle" style="color: {% if standing.gdif < 0 %}red{% elif standing.gdif > 0 %}green{% endif %}">
          {{ standing.gdif }}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

futbol/templates/views/stats_goals_view.html
{% load static %}

<table class="table table-bordered table-condensed shadow-sm">
  <thead>
    <tr>
      <th class="text-center"></th>
      <th class="text-center">Nombre</th>
      <th class="text-center">Equipo</th>
      <th class="text-center">Goles Totales</th>
      <th class="text-center">Penaltis</th>
    </tr>
  </thead>
  <tbody>
    {% for goal in goals %}
      <tr>
        <td class="text-center">
          <img style="height: 48; width: 48px" src="{% static 'futbol/images/players/' %}{{ goal.player__imagen|default:'na' }}.png" class="rounded" alt="Logo" /> <br />
        </td>
        <td class="text-center align-middle">{{ goal.player__name }}</td>
        <td class="text-center align-middle">
          <img style="height: 24; width: 24px" src="{% static 'futbol/images/logos/' %}{{ goal.player__playerleagueteam__team__imagen|default:'na' }}.png" class="rounded" alt="Logo" />
          {{ goal.player__team__name }} 
        </td>
        <td class="text-center align-middle">{{ goal.goals }}</td>
        <td class="text-center align-middle">{{ goal.penalties }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>